export const BIBLE_BOOKS = [
  { label: "Genesis (ഉല്പത്തി)", value: "genesis" },
  { label: "Exodus (പുറപ്പാട്)", value: "exodus" },
  { label: "Leviticus (ലേവ്യപുസ്തകം)", value: "leviticus" },
  { label: "Numbers (സംഖ്യകൾ)", value: "numbers" },
  { label: "Deuteronomy (ആവർത്തനം)", value: "deuteronomy" },
  { label: "Joshua (യോശുവാ)", value: "joshua" },
  { label: "Judges (ന്യായാധിപന്മാർ)", value: "judges" },
  { label: "Ruth (രൂത്ത്)", value: "ruth" },
  { label: "1 Samuel (1 ശമൂവേൽ)", value: "1_samuel" },
  { label: "2 Samuel (2 ശമൂവേൽ)", value: "2_samuel" },
  { label: "1 Kings (1 രാജാക്കൻമാർ)", value: "1_kings" },
  { label: "2 Kings (2 രാജാക്കൻമാർ)", value: "2_kings" },
  { label: "1 Chronicles (1 ദിനവൃത്താന്തം)", value: "1_chronicles" },
  { label: "2 Chronicles (2 ദിനവൃത്താന്തം)", value: "2_chronicles" },
  { label: "Ezra (എസ്രാ)", value: "ezra" },
  { label: "Nehemiah (നെഹെമ്യാവ്)", value: "nehemiah" },
  { label: "Tobit (തോബി)", value: "tobit" },
  { label: "Judith (യൂദിത്)", value: "judith" },
  { label: "Esther (എസ്ഥേർ)", value: "esther" },
  { label: "1 Maccabees (1 മക്കബായർ)", value: "1_maccabees" },
  { label: "2 Maccabees (2 മക്കബായർ)", value: "2_maccabees" },
  { label: "Job (ഇയ്യോബ്)", value: "job" },
  { label: "Psalms (സങ്കീർത്തനങ്ങൾ)", value: "psalms" },
  { label: "Proverbs (സദൃശ്യവാക്യങ്ങൾ)", value: "proverbs" },
  { label: "Ecclesiastes (സഭാപ്രസംഗി)", value: "ecclesiastes" },
  { label: "Song of Solomon (ഉത്തമഗീതം)", value: "song_of_solomon" },
  { label: "Wisdom (ജ്ഞാനസൂക്തങ്ങൾ)", value: "wisdom" },
  { label: "Sirach (സിറാക്)", value: "sirach" },
  { label: "Isaiah (യെശയാവ്)", value: "isaiah" },
  { label: "Jeremiah (യിരമ്യാവ്)", value: "jeremiah" },
  { label: "Lamentations (വിലാപം)", value: "lamentations" },
  { label: "Baruch (ബാറൂക്ക്)", value: "baruch" },
  { label: "Ezekiel (യെഹെസ്ക്കേൽ)", value: "ezekiel" },
  { label: "Daniel (ദാനീയേൽ)", value: "daniel" },
  { label: "Hosea (ഹോശെയ)", value: "hosea" },
  { label: "Joel (യോവേൽ)", value: "joel" },
  { label: "Amos (ആമോസ്)", value: "amos" },
  { label: "Obadiah (ഒബദ്യാവു)", value: "obadiah" },
  { label: "Jonah (യോനാ)", value: "jonah" },
  { label: "Micah (മീഖായാ)", value: "micah" },
  { label: "Nahum (നാഹൂം)", value: "nahum" },
  { label: "Habakkuk (ഹബക്കൂക്ക്)", value: "habakkuk" },
  { label: "Zephaniah (സെഫന്യാവ്)", value: "zephaniah" },
  { label: "Haggai (ഹഗ്ഗായ്)", value: "haggai" },
  { label: "Zechariah (സെഖർയ്യാവ്)", value: "zechariah" },
  { label: "Malachi (മലാക്കി)", value: "malachi" },
  { label: "Matthew (മത്തായി)", value: "matthew" },
  { label: "Mark (മർക്കോസ്)", value: "mark" },
  { label: "Luke (ലൂക്കാ)", value: "luke" },
  { label: "John (യോഹന്നാൻ)", value: "john" },
  { label: "Acts (അപ്പ. പ്രവര്‍ത്തനങ്ങള്‍)", value: "acts" },
  { label: "Romans (റോമാക്കാർ)", value: "romans" },
  { label: "1 Corinthians (1 കൊരിന്ത്യർ)", value: "1_corinthians" },
  { label: "2 Corinthians (2 കൊരിന്ത്യർ)", value: "2_corinthians" },
  { label: "Galatians (ഗലാത്യർ)", value: "galatians" },
  { label: "Ephesians (എഫെസ്യർ)", value: "ephesians" },
  { label: "Philippians (ഫിലിപ്പിയർ)", value: "philippians" },
  { label: "Colossians (കൊലോസ്യർ)", value: "colossians" },
  { label: "1 Thessalonians (1 തെസ്സലോനിക്ക്യർ)", value: "1_thessalonians" },
  { label: "2 Thessalonians (2 തെസ്സലോനിക്ക്യർ)", value: "2_thessalonians" },
  { label: "1 Timothy (1 തിമോത്തി)", value: "1_timothy" },
  { label: "2 Timothy (2 തിമോത്തി)", value: "2_timothy" },
  { label: "Titus (തീത്തൊസ്)", value: "titus" },
  { label: "Philemon (ഫിലേമോൻ)", value: "philemon" },
  { label: "Hebrews (എബ്രായർ)", value: "hebrews" },
  { label: "James (യാക്കോബ്)", value: "james" },
  { label: "1 Peter (1 പത്രോസ്)", value: "1_peter" },
  { label: "2 Peter (2 പത്രോസ്)", value: "2_peter" },
  { label: "1 John (1 യോഹന്നാൻ)", value: "1_john" },
  { label: "2 John (2 യോഹന്നാൻ)", value: "2_john" },
  { label: "3 John (3 യോഹന്നാൻ)", value: "3_john" },
  { label: "Jude (യൂദാസ്)", value: "jude" },
  { label: "Revelation (വെളിപ്പാട്)", value: "revelation" },
];
