export const BIBLE_BOOKS = [
  { label: "Genesis", value: "genesis" },
  { label: "Exodus", value: "exodus" },
  { label: "Leviticus", value: "leviticus" },
  { label: "Numbers", value: "numbers" },
  { label: "Deuteronomy", value: "deuteronomy" },
  { label: "Joshua", value: "joshua" },
  { label: "Judges", value: "judges" },
  { label: "Ruth", value: "ruth" },
  { label: "1 Samuel", value: "1_samuel" },
  { label: "2 Samuel", value: "2_samuel" },
  { label: "1 Kings", value: "1_kings" },
  { label: "2 Kings", value: "2_kings" },
  { label: "1 Chronicles", value: "1_chronicles" },
  { label: "2 Chronicles", value: "2_chronicles" },
  { label: "Ezra", value: "ezra" },
  { label: "Nehemiah", value: "nehemiah" },
  { label: "Tobit", value: "tobit" },
  { label: "Judith", value: "judith" },
  { label: "Esther", value: "esther" },
  { label: "1 Maccabees", value: "1_maccabees" },
  { label: "2 Maccabees", value: "2_maccabees" },
  { label: "Job", value: "job" },
  { label: "Psalms", value: "psalms" },
  { label: "Proverbs", value: "proverbs" },
  { label: "Ecclesiastes", value: "ecclesiastes" },
  { label: "Song of Solomon", value: "song_of_solomon" },
  { label: "Wisdom", value: "wisdom" },
  { label: "Sirach", value: "sirach" },
  { label: "Isaiah", value: "isaiah" },
  { label: "Jeremiah", value: "jeremiah" },
  { label: "Lamentations", value: "lamentations" },
  { label: "Baruch", value: "baruch" },
  { label: "Ezekiel", value: "ezekiel" },
  { label: "Daniel", value: "daniel" },
  { label: "Hosea", value: "hosea" },
  { label: "Joel", value: "joel" },
  { label: "Amos", value: "amos" },
  { label: "Obadiah", value: "obadiah" },
  { label: "Jonah", value: "jonah" },
  { label: "Micah", value: "micah" },
  { label: "Nahum", value: "nahum" },
  { label: "Habakkuk", value: "habakkuk" },
  { label: "Zephaniah", value: "zephaniah" },
  { label: "Haggai", value: "haggai" },
  { label: "Zechariah", value: "zechariah" },
  { label: "Malachi", value: "malachi" },
  { label: "Matthew", value: "matthew" },
  { label: "Mark", value: "mark" },
  { label: "Luke", value: "luke" },
  { label: "John", value: "john" },
  { label: "Acts", value: "acts" },
  { label: "Romans", value: "romans" },
  { label: "1 Corinthians", value: "1_corinthians" },
  { label: "2 Corinthians", value: "2_corinthians" },
  { label: "Galatians", value: "galatians" },
  { label: "Ephesians", value: "ephesians" },
  { label: "Philippians", value: "philippians" },
  { label: "Colossians", value: "colossians" },
  { label: "1 Thessalonians", value: "1_thessalonians" },
  { label: "2 Thessalonians", value: "2_thessalonians" },
  { label: "1 Timothy", value: "1_timothy" },
  { label: "2 Timothy", value: "2_timothy" },
  { label: "Titus", value: "titus" },
  { label: "Philemon", value: "philemon" },
  { label: "Hebrews", value: "hebrews" },
  { label: "James", value: "james" },
  { label: "1 Peter", value: "1_peter" },
  { label: "2 Peter", value: "2_peter" },
  { label: "1 John", value: "1_john" },
  { label: "2 John", value: "2_john" },
  { label: "3 John", value: "3_john" },
  { label: "Jude", value: "jude" },
  { label: "Revelation", value: "revelation" },
];
